Layout/EmptyLines:
   Enabled: false

Layout/EmptyLinesAroundBlockBody:
   Enabled: false

Layout/EmptyLineAfterGuardClause:
   Enabled: false

Layout/IndentationWidth:
   Width: 3

Layout/LeadingCommentSpace:
   Enabled: false

Metrics/AbcSize:
   Enabled: false

Metrics/LineLength:
   Max: 160

Metrics/MethodLength:
   Enabled: false

Performance/StringReplacement:
   Enabled: false

Style/AndOr:
   Enabled: false

Style/Documentation:
   Enabled: false

Style/MultilineTernaryOperator:
   Enabled: false

Style/NegatedIf:
   Enabled: false

Style/Not:
   Enabled: false

Style/RedundantReturn:
   Enabled: false

Style/RescueStandardError:
   Enabled: false

Style/StringLiterals:
   Enabled: false
