Layout/EmptyLines:
   Enabled: false

Layout/EmptyLinesAroundBlockBody:
   Enabled: false

Layout/EmptyLineAfterGuardClause:
   Enabled: false

Layout/IndentationWidth:
   Width: 3

Layout/LeadingCommentSpace:
   Enabled: false

Layout/MultilineMethodCallIndentation:
   EnforcedStyle: indented

Metrics/AbcSize:
   Enabled: false

Metrics/BlockLength:
   Max: 50

Layout/LineLength:
   Max: 160

Metrics/MethodLength:
   Enabled: false

Style/AndOr:
   Enabled: false

Style/Documentation:
   Enabled: false

Style/MultilineTernaryOperator:
   Enabled: false

Style/NegatedIf:
   Enabled: false

Style/Not:
   Enabled: false

Style/RedundantReturn:
   Enabled: false

Style/RescueStandardError:
   Enabled: false

Style/StringLiterals:
   Enabled: false

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

Lint/EmptyBlock: # (new in 1.1)
  Enabled: true

Lint/EmptyClass: # (new in 1.3)
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true

Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true

Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

Style/CollectionCompact: # (new in 1.2)
  Enabled: true

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true

Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true

Style/NilLambda: # (new in 1.3)
  Enabled: true

Style/RedundantArgument: # (new in 1.4)
  Enabled: true

Style/SwapValues: # (new in 1.1)
  Enabled: true
