#!/bin/bash

# Wait for MPD state changes then send desktop notifications with song artist/title
# --hint=int:transient:1 should make the notification go away instead of needing to clear it

while true; do
   notify-send --icon=/usr/share/icons/Yaru/256x256/apps/music-app.png \
	   --hint=int:transient:1 "$(mpc current)"
   mpc idle player
done
